<?php
$main_url_root="http://127.0.0.1/iZend2/";
$main_base_path="/iZend2/";
$main_document_root="/Users/jmlefevre/Documents/workspace/iZend2";
$main_db_host="127.0.0.1";
$main_db_port="3306";
$main_db_name="izend2";
$main_db_user="root";
$main_db_pass="";
$main_db_type="mysqli";
$main_db_character_set="utf8";
$character_set_client="utf8";
$main_db_collation="utf8_general_ci";
$admin_keyword='admin';
?>